### ISSUE TITLE
Consider - one line or two lines for Mayor Brandon Scott's 100 Days of Action

### ISSUE THREAD

**Issue by bhellweg** [city-of-baltimore/transition-agenda#4]
https://github.com/city-of-baltimore/transition-agenda/blob/aada74476bad99fdfc992d7915a7ea3e483fbc8c/ui.R#L58

Personally I prefer one line since we'll have less content now that the photo on the left is gone.

**Comment by schultzhenry** [comment]
Agree. I had made the header text two lines to allow for more vertical height for the City logo with Mayor Scott's name. Since we haven't been formally asked to use the logo with Mayor Scott's name, I preserved the City logo and switched back the header text to one line. I think we can stick with this unless asked for the other logo.

I would also suggest removing the Mayor's first name from the title, as the text is quite long and wraps around on mobile or smaller width browser windows.
